import type { Hunk, PrSnapshot, PrefilteredFile, RepoConfig } from '@prisma-bot/shared';
import type { ChangedFile, ChangedHunk } from '@prisma-bot/shared';
import picomatch from 'picomatch';

/**
 * `PREFILTER_MODULE` — module marker preserved for the existing smoke test
 * (see `packages/core/tests/smoke.test.ts`). The Phase 4 stub exported only
 * this constant; Phase 5.4 keeps it stable for backward compatibility.
 */
export const PREFILTER_MODULE = 'prefilter';

/**
 * `runPrefilter` — deterministic, pure function. Given a `PrSnapshot` and a
 * resolved `RepoConfig`, returns either an `accepted` outcome carrying the
 * `PrefilteredFile[]` ready to feed `Provider.review`, or an `oversized`
 * outcome that the caller must convert to a summary-only fallback per
 * `docs/publication-policy.md` § Diff too large.
 *
 * Per `docs/architecture-decision-records/adr-003-validation-ranking.md`
 * § Pipeline shape (1. Prefilter): "if everything in the diff is excluded by
 * paths, globs, generated-file detection, or size rules, the pipeline ends
 * here without invoking the provider". The caller observes that condition by
 * checking that `accepted.files.length === 0`.
 *
 * Lockfile policy: lockfiles are skipped unconditionally, independent of
 * `exclude_generated`. Lockfiles are pure noise for review purposes (every PR
 * touching dependencies regenerates them), and the rule does not vary across
 * deployments. This is a deliberate Phase 5 baseline rule documented here.
 */

export interface PrefilterSkipped {
  path: string;
  reason:
    | 'binary'
    | 'lockfile'
    | 'generated'
    | 'vendored'
    | 'path_rule_excluded'
    | 'path_rule_not_included'
    | 'removed_file'
    | 'no_hunks';
  detail?: string;
}

export type PrefilterOutcome =
  | {
      kind: 'accepted';
      files: PrefilteredFile[];
      skipped: PrefilterSkipped[];
    }
  | {
      kind: 'oversized';
      reason: 'too_many_files' | 'too_many_changed_lines';
      files_considered: number;
      lines_considered: number;
      skipped: PrefilterSkipped[];
    };

export interface PrefilterMatchers {
  isLockfile?: (path: string) => boolean;
  isGenerated?: (path: string, content?: string) => boolean;
  isVendored?: (path: string) => boolean;
}

export interface PrefilterOptions {
  snapshot: PrSnapshot;
  config: RepoConfig;
  /** override the lockfile / generated / vendor matchers (for tests). */
  matchers?: PrefilterMatchers;
  /**
   * Optional resolver that returns the textual content for a hunk. The
   * snapshotter (Phase 5.5) wires this with its diff text; in Phase 5.4 it is
   * absent and `Hunk.content` is left as the empty string. The downstream
   * provider adapter does not depend on `content` being non-empty.
   */
  hunkContent?: (path: string, hunk: ChangedHunk) => string;
}

/**
 * Default lockfile basenames. Match by basename only (case-sensitive). The
 * list is the union of common ecosystems' lockfile names; adding a new
 * ecosystem to this list is a one-line change with no behavioural risk.
 */
const DEFAULT_LOCKFILES = new Set<string>([
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'npm-shrinkwrap.json',
  'Cargo.lock',
  'Gemfile.lock',
  'Pipfile.lock',
  'poetry.lock',
  'composer.lock',
  'go.sum',
  'mix.lock',
  'Podfile.lock',
  'flake.lock',
  'bun.lockb',
]);

const VENDORED_SEGMENTS = [
  'vendor/',
  'third_party/',
  'node_modules/',
  'bower_components/',
  '.git/',
  '.bundle/',
];

const GENERATED_GLOBS = [
  '**/*.pb.go',
  '**/*.pb.ts',
  '**/*.gen.ts',
  '**/*.gen.go',
  '**/*.generated.*',
  'dist/**',
  'build/**',
  '__generated__/**',
  'coverage/**',
  '**/*.min.js',
  '**/*.min.css',
  '**/*.lock',
  '**/.next/**',
  '**/openapi.json',
];

const GENERATED_CONTENT_MARKERS = [
  /\/\/\s*Code generated/i,
  /\/\/\s*DO NOT EDIT/i,
  /#\s*generated by/i,
];

const defaultIsLockfile = (path: string): boolean => {
  const basename = path.split('/').pop() ?? path;
  return DEFAULT_LOCKFILES.has(basename);
};

const defaultIsVendored = (path: string): boolean => {
  // Match a vendored segment anywhere in the path (start or after a separator).
  for (const segment of VENDORED_SEGMENTS) {
    if (path === segment.slice(0, -1)) return true;
    if (path.startsWith(segment)) return true;
    if (path.includes(`/${segment}`)) return true;
  }
  return false;
};

const generatedMatchers = GENERATED_GLOBS.map((glob) => picomatch(glob, { dot: true }));

const defaultIsGenerated = (path: string, content?: string): boolean => {
  for (const match of generatedMatchers) {
    if (match(path)) return true;
  }
  if (content !== undefined) {
    const head = content.slice(0, 1024);
    for (const re of GENERATED_CONTENT_MARKERS) {
      if (re.test(head)) return true;
    }
  }
  return false;
};

const compileGlobs = (patterns: readonly string[]): ((path: string) => boolean) => {
  if (patterns.length === 0) return () => false;
  const matchers = patterns.map((p) => picomatch(p, { dot: true }));
  return (path: string) => matchers.some((m) => m(path));
};

const buildHunkId = (path: string, hunk: ChangedHunk): string => {
  // The id encodes the new-file line range for the hunk: stable across runs and
  // unique per (path, range). The validator checks `line ∈ [new_start, new_start + new_lines)`
  // against this same arithmetic; see `packages/core/src/validator-ranker/validator/index.ts`.
  const end = hunk.new_start + hunk.new_lines;
  return `${path}#${hunk.new_start}-${end}`;
};

const toPrefilteredFile = (
  file: ChangedFile,
  hunkContent: PrefilterOptions['hunkContent'],
): PrefilteredFile => {
  const hunks: Hunk[] = file.hunks.map((hunk) => {
    // The ProviderReviewInput Hunk uses [line_start, line_end]; we interpret the
    // ChangedHunk's `new_start` + `new_lines` as the inclusive new-file range.
    // For pure-insertion hunks `new_lines` is positive; if a snapshotter ever
    // produces a zero-length hunk in `new_lines`, we still emit a Hunk with
    // `line_end = line_start` so the schema's positive-int constraint holds.
    const end = hunk.new_start + Math.max(hunk.new_lines, 1) - 1;
    const id = buildHunkId(file.path, hunk);
    const content = hunkContent ? hunkContent(file.path, hunk) : '';
    return {
      id,
      line_start: hunk.new_start,
      line_end: end,
      content,
    };
  });
  const result: PrefilteredFile = {
    path: file.path,
    hunks,
  };
  if (file.language !== undefined) {
    return { ...result, language: file.language };
  }
  return result;
};

interface FileEvaluation {
  file: ChangedFile;
  outcome:
    | { kind: 'kept' }
    | { kind: 'skipped'; reason: PrefilterSkipped['reason']; detail?: string };
}

const evaluateFile = (
  file: ChangedFile,
  config: RepoConfig,
  matchers: Required<PrefilterMatchers>,
  includeMatch: (path: string) => boolean,
  excludeMatch: (path: string) => boolean,
  hasIncludeRules: boolean,
): FileEvaluation['outcome'] => {
  if (file.status === 'removed') return { kind: 'skipped', reason: 'removed_file' };
  if (file.is_binary) return { kind: 'skipped', reason: 'binary' };
  if (excludeMatch(file.path)) return { kind: 'skipped', reason: 'path_rule_excluded' };
  if (hasIncludeRules && !includeMatch(file.path)) {
    return { kind: 'skipped', reason: 'path_rule_not_included' };
  }
  if (config.exclude_vendored && matchers.isVendored(file.path)) {
    return { kind: 'skipped', reason: 'vendored' };
  }
  if (matchers.isLockfile(file.path)) return { kind: 'skipped', reason: 'lockfile' };
  if (config.exclude_generated && matchers.isGenerated(file.path)) {
    return { kind: 'skipped', reason: 'generated' };
  }
  if (file.hunks.length === 0) return { kind: 'skipped', reason: 'no_hunks' };
  return { kind: 'kept' };
};

export const runPrefilter = (opts: PrefilterOptions): PrefilterOutcome => {
  const { snapshot, config } = opts;
  const matchers: Required<PrefilterMatchers> = {
    isLockfile: opts.matchers?.isLockfile ?? defaultIsLockfile,
    isGenerated: opts.matchers?.isGenerated ?? defaultIsGenerated,
    isVendored: opts.matchers?.isVendored ?? defaultIsVendored,
  };
  const includeMatch = compileGlobs(config.path_rules.include);
  const excludeMatch = compileGlobs(config.path_rules.exclude);
  const hasIncludeRules = config.path_rules.include.length > 0;

  const skipped: PrefilterSkipped[] = [];
  const kept: ChangedFile[] = [];

  for (const file of snapshot.files) {
    const outcome = evaluateFile(
      file,
      config,
      matchers,
      includeMatch,
      excludeMatch,
      hasIncludeRules,
    );
    if (outcome.kind === 'skipped') {
      const entry: PrefilterSkipped = { path: file.path, reason: outcome.reason };
      if (outcome.detail !== undefined) {
        skipped.push({ ...entry, detail: outcome.detail });
      } else {
        skipped.push(entry);
      }
      continue;
    }
    kept.push(file);
  }

  const lines_considered = kept.reduce((sum, f) => sum + f.additions + f.deletions, 0);

  if (kept.length > config.max_files) {
    return {
      kind: 'oversized',
      reason: 'too_many_files',
      files_considered: kept.length,
      lines_considered,
      skipped,
    };
  }
  if (lines_considered > config.max_changed_lines) {
    return {
      kind: 'oversized',
      reason: 'too_many_changed_lines',
      files_considered: kept.length,
      lines_considered,
      skipped,
    };
  }

  const files = kept.map((f) => toPrefilteredFile(f, opts.hunkContent));
  return { kind: 'accepted', files, skipped };
};
